#!/bin/sh
# A utility script to edit specific configs
# Rewrite script to fit your configs
# Dependencies:
# rofi


CONFIGS="awesome|bash|neovim|kitty|polybar"
EDIT=$EDITOR

USERINPUT=$(echo $CONFIGS | rofi -sep "|" -dmenu -i -p "Which program would you like to edit the config of?")

case $USERINPUT in
    "awesome")
        $EDIT ~/.config/awesome/rc.lua
        ;;
    "neovim")
        $EDIT ~/.config/nvim/init.vim
        ;;
    "bash")
        $EDIT ~/.config/bash/.bashrc
        ;;
    "kitty") 
        $EDIT ~/.config/kitty/kitty.conf
        ;;
    "polybar")
        $EDIT ~/.config/polybar/config.ini
        ;;
    "*")
        echo "Unknown option"
        ;;
esac
