#!/bin/bash
# A polybar launching script copied from the Arch wiki
# Configure as needed for your bar
# Dependencies:
# polybar

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar jandrew &
