#!/bin/sh
# A utility script to quickly edit other scripts
# Dependencies:
# dmenu

SCRIPTS="configs\ngc\nscripts\nmakeScript\nsyncConfigs"
EDIT=$EDITOR

USERINPUT=$(echo -e $SCRIPTS | dmenu -p "Choose a script to edit")

case $USERINPUT in
    "gc")
        $EDIT ~/Scripts/gc
        ;;
    "configs")
        $EDIT ~/Scripts/configs
        ;;
    "makeScript")
        $EDIT ~/Scripts/makeScript
        ;;
    "syncConfigs")
        $EDIT ~/Scripts/syncConfigs
        ;;
    "scripts")
        $EDIT ~/Scripts/scripts
        ;;
    *)
        echo "Script not found"
        ;;
esac
