#!/bin/sh
# A utility script to quickly edit other scripts
# Dependencies:
# rofi

SCRIPTS="configs|gc|scripts|makeScript|syncConfigs"
EDIT=$EDITOR

USERINPUT=$(echo  $SCRIPTS | rofi -sep "|" -dmenu -i -p "Choose a script to edit")

case $USERINPUT in
    "gc")
        $EDIT ~/Scripts/gc
        ;;
    "configs")
        $EDIT ~/Scripts/configs
        ;;
    "makeScript")
        $EDIT ~/Scripts/makeScript
        ;;
    "syncConfigs")
        $EDIT ~/Scripts/syncConfigs
        ;;
    "scripts")
        $EDIT ~/Scripts/scripts
        ;;
    *)
        echo "Script not found"
        ;;
esac
