#!/bin/sh
# A utility script that syncs my configs to the git repo

GIT="cd ~/Repos/dotfiles && git add . && git commit -m 'config update' && git push && cd"
CONFIGS="alacritty\nawesome\nbash\nnvim\npolybar\nzsh\nall"
USERINPUT=$(echo -e "$CONFIGS" | dmenu -p "Which config would you like to sync?")

case $USERINPUT in
    "alacritty") cp -r ~/.config/alacritty ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "awesome") cp -r ~/.config/awesome ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "bash") cp -r ~/.config/bash ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "nvim") cp -rf ~/.config/nvim ~/Repos/dotfiles/.config/ && rm -rf ~/Repos/dotfiles/.config/nvim/autoload/plugged && eval "$GIT" ;;
    "polybar") -r cp ~/.config/polybar ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "zsh") cp -r ~/.config/zsh ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "all") cp -r ~/.config ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "*") echo "Unknown option" && exit 1 ;;
esac
#!/bin/sh



