#!/bin/sh
# A utility script that syncs my configs to the git repo

CONFIGS="kitty|awesome|bash|nvim|polybar|zsh"
USERINPUT=$(echo "$CONFIGS" | rofi -sep "|" -dmenu -p "Which config would you like to sync?")
GIT="cd ~/Repos/dotfiles && git add . && git commit -m '$USERINPUT: update' && git push && cd"

case $USERINPUT in
    "kitty") cp -r ~/.config/kitty ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "awesome") cp -r ~/.config/awesome ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "bash") cp -r ~/.config/bash ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "nvim") cp -r ~/.config/nvim/init.vim ~/Repos/dotfiles/.config/nvim/init.vim && eval "$GIT" ;;
    "polybar") cp -r ~/.config/polybar ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "zsh") cp -r ~/.config/zsh ~/Repos/dotfiles/.config/ && eval "$GIT" ;;
    "*") echo "Unknown option" && exit 1 ;;
esac
